import Services.BetterParser
import Services.CheckIfUserIsStillTyping
import Services.GetTacticSubstring
import Services.GetTheorems
import Services.GoalsAt
import Services.PrettifyRwTactic
import Services.ShouldRenderSingleSequent
